### ISSUE TITLE
Duplicates in nearest stars list

### ISSUE THREAD

**Issue by Allitnil2** [EDDiscovery/EDDiscovery#1579]
See https://i.imgur.com/hpk6WJi.png

Nyautheia TD-Z d1-55 to Nyautheia TD-Z d1-7 are systems that I've just visited this session and are all duplicated. Nyautheia UD-Z d1-38 and the rest are from my last session and are not duplicated.

To recreate: travel to a little visited area and do small jumps so that the nearest known stars are those you have just visited.

**Comment by klightspeed** [comment]
I'm guessing that systems from new journal entries are added to the nearest
system list without checking for duplicates.

On 28 Dec 2017 8:18 PM, "Allitnil2" <notifications@github.com> wrote:

See https://i.imgur.com/hpk6WJi.png

Nyautheia TD-Z d1-55 to Nyautheia TD-Z d1-7 are systems that I've just
visited this session and are all duplicated. Nyautheia UD-Z d1-38 and the
rest are from my last session and are not duplicated.

To recreate: travel to a little visited area and do small jumps so that the
nearest known stars are those you have just visited.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1579>, or mute the thread

**Comment by andreaspada** [comment]
I'm aware of that bug. I noticed it too, and it happens exactly as you sad: traveling to a near system so that the system you just visited appear in the list. I frankly don't have any clue in regard, but I'll give it a look.

**Comment by andreaspada** [comment]
I added some code to a PR (#1573 ) I already posted which hopefully solve that.

**Comment by robbyxp1** [comment]
I've found the original bug, so will incorporate this but remove your duplicate code from the UC.

**Comment by andreaspada** [comment]
That's awesome, @robbyxp1! KUDOS

**Comment by robbyxp1** [comment]
Fixed by PR1592

**Comment by Lethann** [comment]
I know this is closed but i wanted to report that this is still happening as of v 10.3.3.0 (just installed this yesterday)

![edd duplicate visited bug](https://user-images.githubusercontent.com/25929754/50548499-4307b000-0c13-11e9-82b1-654bae2de7c4.JPG)

**Comment by klightspeed** [comment]
Your issue is with duplicates in the ___Visited Stars___ list, whereas this issue was about duplicates in the ___Nearest Stars___ list.

Please create a new issue.
