### ISSUE TITLE
EDDiscovery v9.1.2.0 There was an unhandled UI exception

### ISSUE THREAD

**Issue by chartercook28** [EDDiscovery/EDDiscovery#1771]
### Exception Details:
>EDDiscovery v9.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.StarScan.Process(IBodyNameAndID sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 423
>   at EliteDangerousCore.StarScan.AddBodyToBestSystem(IBodyNameAndID je, Int32 startindex, List`1 hl, HistoryEntry& he, JournalLocOrJump& jl) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 273
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 811
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 463
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 444
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
Try 9.1.4 it should be solved.

**Comment by zukakog** [comment]
I'm still getting the same error with 9.1.5.0.

### Exception Details:
EDDiscovery v9.1.5.0 There was an unhandled UI exception.
`==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 247
   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 269
   at EDDiscovery.UserControls.UserControlSynthesis.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 164
   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 333
   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 192
   at System.Action`1.Invoke(T obj)
   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 845
===== END =====`

**Comment by klightspeed** [comment]
@zukakog that issue is different to that in the OP.

It suggests you are landed on a planet that hasn't been scanned with a detailed surface scanner.  At https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlShoppingList.cs#L245, we need to make sure the scan actually has materials.

**Comment by klightspeed** [comment]
@zukakog your issue should be fixed in v9.1.6 (#1792)
