### ISSUE TITLE
Captains Log

### ISSUE THREAD

**Issue by IXIDoctorIXI** [EDDiscovery/EDDiscovery#3030]
There was an unhandled UI exception.

==== BEGIN ====
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en EDDiscovery.UserControls.CaptainsLogDiary.LoadLayout() en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogDiary.cs:línea 58
   en EDDiscovery.UserControls.UserControlCaptainsLog.<Init>b__6_1(TabStrip tab, Control ctrl, Int32 si) en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\UserControlCaptainsLog.cs:línea 54
   en ExtendedControls.TabStrip.PostCreate() en C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:línea 198
   en ExtendedControls.TabStrip.ChangePanel(Int32 i) en C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:línea 130
   en EDDiscovery.UserControls.UserControlForm.UserControlForm_Shown(Object sender, EventArgs e) en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Form\UserControlForm.cs:línea 297
   en System.Windows.Forms.Form.OnShown(EventArgs e)
   en System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   en System.Windows.Forms.Control.InvokeMarshaledCallbacks()
===== END =====

**Comment by Eahlstan** [comment]
So what did you do when this popped up? Are you using any translations? Is this reproducable?

**Comment by IXIDoctorIXI** [comment]
> So what did you do when this popped up? Are you using any translations? Is this reproducable?

I use translation.

**Comment by Eahlstan** [comment]
So could you please try if this happens in the english version too?
Also please specify which language you are using.

**Comment by IXIDoctorIXI** [comment]
oooo... thanks... i fixed the problem :)

**Comment by IXIDoctorIXI** [comment]
Thanks for the help :)

**Comment by Eahlstan** [comment]
That didn't fix anything.
If this doesn't happen in the english version then something is wrong in the language files.
So please tell us which language you were using.

**Comment by IXIDoctorIXI** [comment]
> That didn't fix anything.
> If this doesn't happen in the english version then something is wrong in the language files.
> So please tell us which language you were using.

Excuse me, I forgot that I was using the Spanish translation that I have been working on and thanks to what you told me, I compared the original with mine and I was able to fix the problem quickly.
That's why I reported the problem, I thought it was from the app but when you told me about the English version I verified it and in the end it was a minimal error that semicolons were missing on the days of the week.

**Comment by Eahlstan** [comment]
Ah. I didn't know that :)

Thanks for your reply.

**Comment by IXIDoctorIXI** [comment]
> Ah. I didn't know that :)
> 
> Thanks for your reply.

Anyway, I am Doctor Smile#0469 in discord.
