### ISSUE TITLE
6.1.2.0 - Each time I try to open S-Panel I get an exception

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#896]
I hadn't tried re-enabling the S-Panel since the exceptions in 6.1.1.  But trying now, it seems to throw an exception every time.  If I click ignore, the panel does open but unresponsive, and the main program starts having drawing issues.  Note, this is a fresh new panel, not trying to restore one from previous.
I *can* open the trip panel ok though.   

http://i.imgur.com/6jmu3vv.png

http://i.imgur.com/FqW28Uq.png

[Trace_20170308060700.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/825501/Trace_20170308060700.0.txt)

**Comment by klightspeed** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a45dfb8a-7ae8-4155-b345-45c146001c22/systemargumentexception-from-systemdrawingimagegetwidth?forum=vcgeneral suggests this can be caused by the image being disposed at some point.
@phroggster @robbyxp1 is the image returned by JournalEntry.GetIcon() disposed by anything?  The images returned by GetIcon() are owned by the resource manager, and should never be disposed.

**Comment by finwen** [comment]
Should be solved in 6.1.3

**Comment by skwerlman** [comment]
I am still seeing a crash when opening S-Panell in 6.1.3: http://puu.sh/uSv4r/23e7cda37c.png
